FROM oven/bun:1.3.10

WORKDIR /app


COPY package.json bun.lock turbo.json ./


COPY packages ./packages


COPY apps/dbWorker ./apps/dbWorker

RUN bun install 

WORKDIR /app/apps/dbWorker

CMD ["bun", "run", "src/index.ts"]
