FROM oven/bun:1.3.10

WORKDIR /app


COPY package.json bun.lock turbo.json ./


COPY packages ./packages


COPY apps/engine ./apps/engine

RUN bun install 

WORKDIR /app/apps/engine



CMD ["bun", "run", "src/index.ts"]