name: perps

services:
  postgres:
    image: postgres
    container_name: perps-postgres
    restart: always
    environment:
      POSTGRES_DB: perps_exchange
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: perps
    ports:
      - "5432:5432"
    volumes:
      - perps-postgres-data:/var/lib/postgresql

  redis:
    image: redis
    container_name: perps-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - perps-redis-data:/data

  backend:
    build:
      context: .
      dockerfile: ./apps/backend/dockerfile.prod.backend
    container_name: perps-backend
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - .env.prod
    depends_on:
      - postgres
      - redis

  engine:
    build:
      context: .
      dockerfile: ./apps/engine/dockerfile.prod.engine
    container_name: perps-engine
    restart: always
    env_file:
      - .env.prod
    depends_on:
      - redis
    volumes:
      - engine-snapshots:/app/apps/engine/snapshots

  dbworker:
    build:
      context: .
      dockerfile: ./apps/dbWorker/dockerfile.prod.dbworker
    container_name: perps-dbworker
    restart: always
    env_file:
      - .env.prod
    depends_on:
      - postgres
      - redis

  wsgateway:
    build:
      context: .
      dockerfile: ./apps/wsGateway/dockerfile.prod.wsgateway
    container_name: perps-wsgateway
    restart: always
    ports:
      - "3002:3002"
    env_file:
      - .env.prod
    depends_on:
      - redis

  priceworker:
    build:
      context: .
      dockerfile: ./apps/priceWorker/dockerfile.prod.priceworker
    container_name: perps-priceworker
    restart: always
    env_file:
      - .env.prod
    depends_on:
      - redis

volumes:
  engine-snapshots:
  perps-postgres-data:
  perps-redis-data:
