FROM oven/bun:1.3.10

WORKDIR /app

COPY package.json bun.lock turbo.json ./
COPY packages ./packages
COPY apps/backend ./apps/backend

RUN bun install

EXPOSE 3001

CMD ["sh", "-c", "bun run db:generate && bun run db:migrate && cd apps/backend && bun run start"]