FROM oven/bun:1.3.10

WORKDIR /app

# workspace files
COPY package.json bun.lock turbo.json ./

# shared packages
COPY packages ./packages


COPY apps/priceWorker ./apps/priceWorker

RUN bun install 

WORKDIR /app/apps/priceWorker


CMD ["bun", "run", "src/index.ts"]
