services:
  postgres:
    image: postgres
    container_name: perps-postgres
    restart: always
    environment:
      POSTGRES_DB: perps_exchange
      POSTGRES_PASSWORD: perps
    ports:
      - "5432:5432"
    volumes:
      - perps-postgres-data:/var/lib/postgresql

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: perps-timescaledb
    restart: always
    environment:
      POSTGRES_PASSWORD: perps
      POSTGRES_DB: perps_market_data
    ports:
      - "5433:5432"
    volumes:
      - perps-timescale-data:/var/lib/postgresql/data
      
  redis:
    image: redis
    container_name: perps-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - perps-redis-data:/data

volumes:
  perps-postgres-data:
  perps-redis-data:
  perps-timescale-data: