FROM oven/bun:1.3.10

WORKDIR /app


COPY package.json bun.lock turbo.json ./


COPY packages ./packages


COPY apps/wsGateway ./apps/wsGateway

RUN bun install 

WORKDIR /app/apps/wsGateway



CMD ["bun", "run", "src/index.ts"]